<?php
    echo "<br>";
    echo "<br>";
    echo "<form method='post' action='' >";
        echo "<input type='hidden' name='thong_tin_khach_hang' value='co' > ";
        echo "<table style='line-height: 1.5em;'>";
            echo "<tr>";
                echo "<th colspan='2' height='30px' class='text-brand fs-5'>";
                    echo "Thông tin mua hàng";
                echo "</th>";
            echo "</tr>";
            echo "<tr class='mt-2'>";
                echo "<td width='180px'>Tên người mua :</td>";
                echo "<td>";
                    echo "<input type='text' style='width:400px' name='ten_nguoi_mua' required>";
                echo "</td>";
            echo "</tr>";
            echo "<tr>";
                echo "<td>Email : </td>";
                echo "<td>";
                    echo "<input type='text' style='width:400px' name='email'>";
                echo "</td>";
            echo "</tr>";
            echo "<tr>";
                echo "<td>Địa chỉ : </td>";                  
                echo "<td>";
                    echo "<textarea style='width:400px;' name='dia_chi' required></textarea>";
                echo "</td>";
            echo "</tr>";
            echo "<tr>";
                echo "<td>Điện thoại : </td>";
                echo "<td>";
                    echo "<input type='text' style='width:400px' name='dien_thoai' required>";
                echo "</td>";
            echo "</tr>";
            echo "<tr>";
                echo "<td>Chú thích cho shop :</td>";
                echo "<td>";
                    echo "<textarea style='width:400px;height:100px' name='noi_dung' ></textarea>";
                echo "</td>";
            echo "</tr>";
            echo "<tr>";
                echo "<td>&nbsp;</td>";
                echo "<td style='text-align: center;'>";
                    echo "<input type='submit' value='Mua hàng' class='btn btn-brand'>";
                echo "</td>";
            echo "</tr>";
        echo "</table>";
    echo "</form>";
?>